Feat/3 feat: make siginup
jungle-6-3/code-sync-be pull request #7
Opened 2024-10-20 10:02 UTC by HyoungUkJo

#Signup create
---
회원가입 기능 구현

2024-10-20 14:49 UTC, loopy-lim requested changes
일단 볼 수 있는 부분은 보았습니다. 개인적으로 수정하면 좋을 부분과, 한번 더 생각해보면 좋을 부분을 넣어두었습니다.

생각해볼만한 점을 추가적으로 적자면 다음과 같습니다.
- auth와 user의 차이가 무엇인가요?
- auth에서 하는 역활은 무엇인가요?
- user에서 하는 역활은 무엇인가요?
- 주석은 어떤 것일까요?
- 서비스는 무엇일까요?
- bycript도 하나의 서비스가 아닐까요?

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/auth.controller.ts
> +    return
혹시... linter는 적용 하셨나용? `;`가 빠져서 말씀드립니다.

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/auth.controller.ts
> +    }
한번 nest에서도 빌드 패턴이 있는지 확인하면 더 깔끔한 코드가 되지 않을까요? 
추가적으로 error를 early return하면 더욱 깔끔한 코드가 될 것 같아요.

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/auth.controller.ts
> +    console.log(result);
PR을 올릴때는 console.log와 같은 log들은 빼는 것이 좋습니다.

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/auth.controller.ts
> +  withdraw(): AuthResponseDto {
이 함수를 직접적으로 불러 사용하지 않고 앞뒤 맥락을 통해 알 수 있긴 합니다.
그럼에도 불구하고 맥락을 유지하며 좋기에, 함수명을 변경하면 좋을 것 같아요.

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/auth.service.ts
> +    }
좋아요! 위에서 말했던 early return을 적용하였군요.
return false대신에 throw new Error()와 같이 작성하셨으면 다음에 리펙토링할 때 더 편할 것이에요!!
만약에 다음에 여기에 할일을 추가해야한다! 라면 `TODO: 할일`, `FIXME: 할일` 와 같은 주석을 추가해주세요.

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/dto/signup-request.dto.ts
> +    description: 'user email',
괜한 트집이지만, description은 한가지로 통일하면 좋을 것 같아요!
위에서는 한글이지만, 여기서는 영어네용(사실 그냥 트집이라서 넘기셔도 됩니다!!)

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/dto/signup-request.dto.ts
> +  name: string;
오오.....
이런기능 있는건 처음 알았어요

2024-10-20 14:49 UTC, loopy-lim commented on src/auth/dto/signup-request.dto.ts
> -  @IsNotEmpty()
이것을 뺀 이유는 무엇인가요??? password는 회원가입할때 무조건 있어야 하는 것이 아닌가요?

2024-10-20 14:49 UTC, loopy-lim commented on src/main.ts
> +  // dto 유효성 확인
이것도 괜한 트집이지만, 주석은 최대한 지양하면 좋을 것 같아요.
저의 경우에는 코드에서 충분히 설명이 가능하게 하는 것을 좋아합니다. 써야하는 경우에는 큼지막하게 나누어야 하는 것이나, 설명해야 이해하는 부분의 경우에 넣습니다.

2024-10-20 14:49 UTC, loopy-lim commented on src/users/users.controller.ts
> +}
모두 있어도 됩니다(사실 아님). 판단해서 지워야하는 부분은 지워주세요.
새로 들어온 코드가 깔끔해야 추후에 비용이 크게 안늘어날꺼에요

2024-10-20 15:08 UTC, HyoungUkJo commented on src/auth/auth.controller.ts
> +    return
ㄷㄷㄷㄷ;;; 안했나보네요... 지금은 또 되어있는데,,, 펑,,,,

2024-10-20 15:08 UTC, HyoungUkJo commented on src/auth/auth.controller.ts
> +    }
확인해보겠습니다!

2024-10-20 15:08 UTC, HyoungUkJo commented on src/auth/auth.controller.ts
> +    console.log(result);
넵!

2024-10-20 15:10 UTC, HyoungUkJo commented on src/auth/auth.service.ts
> +    }
일단 로그인 기능을 다 만든다음 창근님이랑 exception 이야기 해보려고 했습니다. 이 부분도 다시 생각해 보겠습니다.

2024-10-20 15:13 UTC, HyoungUkJo commented on src/auth/dto/signup-request.dto.ts
> +    description: 'user email',
오잇? 어디 부분인지.. 일단 descripton은 다 영어로 하려고합니다!

2024-10-20 15:14 UTC, HyoungUkJo commented on src/auth/dto/signup-request.dto.ts
> -  @IsNotEmpty()
pipe에서 dto를 기준으로 validate를 하기때문에 필요 없다고 생각해서 일단 뺐습니다.

2024-10-20 15:14 UTC, HyoungUkJo commented on src/main.ts
> +  // dto 유효성 확인
수정하겠습니다!

2024-10-20 15:14 UTC, HyoungUkJo commented on src/users/users.controller.ts
> +}
아.. 이거 지운다는걸 그냥 올려버렸네요.. 수정하겠습니다.

2024-10-21 01:27 UTC, loopy-lim commented on src/auth/dto/signup-request.dto.ts
> -  @IsNotEmpty()
어... 그래서 필요한것이 아닌가요???

2024-10-21 05:24 UTC, closed without merging